"""empty message

Revision ID: 007403456b3d
Revises: db70a8200c1e
Create Date: 2022-08-10 13:04:19.442086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007403456b3d'
down_revision = 'db70a8200c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.drop_column('Artist', 'search_venue')
    op.add_column('Show', sa.Column('start_time', sa.String(), nullable=False))
    op.drop_column('Show', 'starting_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('starting_time', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Show', 'start_time')
    op.add_column('Artist', sa.Column('search_venue', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###
