"""empty message

Revision ID: db70a8200c1e
Revises: 488fe84fb2ae
Create Date: 2022-08-10 11:35:58.131495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db70a8200c1e'
down_revision = '488fe84fb2ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.drop_column('Artist', 'web_site')
    op.drop_column('Artist', 'search_description')
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.drop_column('Venue', 'web_site')
    op.drop_column('Venue', 'search_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('search_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('web_site', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'website_link')
    op.drop_column('Venue', 'seeking_talent')
    op.add_column('Artist', sa.Column('search_description', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('web_site', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'website_link')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
